#!/usr/bin/env python3
"""
tools/fontawesome/subset.py — builds a Font Awesome subset with only the icons
the site uses (~20 KB instead of ~340 KB of fonts + CSS).

    python3 tools/fontawesome/subset.py          # (re)generate the subset
    python3 tools/fontawesome/subset.py --check  # CI: fail if an icon is missing

Icons are found by scanning the tracked sources (layouts, includes, pages,
posts, _config*.yml, _data, JavaScript) for `fa-<name>` classes, plus the
names listed in tools/fontawesome/extra-icons.txt (for icons built at run
time, or used by your own content outside the repository).

Output: assets/vendor/fontawesome/subset/ (fa-subset.css, fa-solid-900.woff2,
fa-brands-400.woff2). The full set stays in assets/vendor/fontawesome/ and is
used instead when `theme_config.icons: full`.
Needs: pip install fonttools brotli
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FA = os.path.join(ROOT, 'assets', 'vendor', 'fontawesome')
OUT = os.path.join(FA, 'subset')
EXTRA = os.path.join(ROOT, 'tools', 'fontawesome', 'extra-icons.txt')
FONTS = {  # font file -> CSS family / weight in the subset
    'fa-solid-900.woff2': ('Font Awesome 6 Free', 900),
    'fa-brands-400.woff2': ('Font Awesome 6 Brands', 400),
}
SKIP = re.compile(r'^(assets/vendor/|tools/fontawesome/|_site/|\.git)|\.(png|jpe?g|gif|webp|avif|ico|svg|woff2?|ttf|eot|wasm|gba|zip|gz)$')


def full_css():
    return open(os.path.join(FA, 'css', 'all.min.css'), encoding='utf-8').read()


def icon_map(css):
    """icon name -> codepoint, from rules such as .fa-home,.fa-house{--fa:"\\f015"}"""
    names = {}
    for sel, cp in re.findall(r'([^{}]+)\{--fa:"\\([0-9a-f]+)"\}', css):
        for s in sel.split(','):
            m = re.fullmatch(r'\s*\.fa-([a-z0-9-]+)\s*', s)
            if m:
                names[m.group(1)] = int(cp, 16)
    return names


def used_names(known):
    files = subprocess.run(['git', 'ls-files'], cwd=ROOT, capture_output=True, text=True, check=True).stdout.split()
    found = set()
    for f in files:
        if SKIP.search(f):
            continue
        try:
            text = open(os.path.join(ROOT, f), encoding='utf-8', errors='ignore').read()
        except OSError:
            continue
        found.update(m for m in re.findall(r'\bfa-([a-z0-9-]+)', text) if m in known)
    if os.path.exists(EXTRA):
        for line in open(EXTRA, encoding='utf-8'):
            name = line.split('#', 1)[0].strip().replace('fa-', '', 1) if line.strip().startswith('fa-') else line.split('#', 1)[0].strip()
            if name:
                if name not in known:
                    sys.exit('extra-icons.txt: unknown icon "%s"' % name)
                found.add(name)
    return found


def manifest():
    path = os.path.join(OUT, 'fa-subset.css')
    if not os.path.exists(path):
        return set()
    m = re.search(r'icons: ([a-z0-9 -]*) \*/', open(path, encoding='utf-8').read())
    return set(m.group(1).split()) if m else set()


def build(css, known, names):
    from fontTools import subset
    from fontTools.ttLib import TTFont
    os.makedirs(OUT, exist_ok=True)
    cps = {known[n] for n in names}
    for fname in FONTS:
        font = TTFont(os.path.join(FA, 'webfonts', fname))
        have = set(font.getBestCmap())
        keep = sorted(cps & have)
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.layout_features = ['*']
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(unicodes=keep)
        sub.subset(font)
        font.flavor = 'woff2'
        font.save(os.path.join(OUT, fname))

    # CSS: everything but the icon rules and @font-face, then our icons / faces
    head = css[:css.index('*/') + 2]
    rules = re.sub(r'@font-face\{[^}]*\}', '', css[css.index('*/') + 2:])

    def keep_rule(m):
        sels = [s for s in m.group(1).split(',')
                if re.fullmatch(r'\s*\.fa-([a-z0-9-]+)\s*', s) and s.strip()[4:] in names]
        return (','.join(sels) + '{--fa:"\\' + m.group(2) + '"}') if sels else ''
    rules = re.sub(r'([^{}]+)\{--fa:"\\([0-9a-f]+)"\}', keep_rule, rules)
    faces = ''.join(
        '@font-face{font-family:"%s";font-style:normal;font-weight:%d;font-display:block;'
        'src:url(%s) format("woff2")}' % (fam, w, f) for f, (fam, w) in FONTS.items())
    out = '%s\n/* subset generated by tools/fontawesome/subset.py — icons: %s */\n%s%s\n' % (
        head, ' '.join(sorted(names)), faces, rules)
    open(os.path.join(OUT, 'fa-subset.css'), 'w', encoding='utf-8').write(out)
    sizes = {f: os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT)}
    print('Font Awesome subset: %d icons — %s' % (len(names), ', '.join('%s %.1f KB' % (f, s / 1024) for f, s in sorted(sizes.items()))))


def main():
    css = full_css()
    known = icon_map(css)
    names = used_names(known)
    if '--check' in sys.argv:
        missing = sorted(names - manifest())
        if missing:
            print('Icons used but missing from the Font Awesome subset: ' + ', '.join(missing))
            print('Run: python3 tools/fontawesome/subset.py (then commit assets/vendor/fontawesome/subset/)')
            sys.exit(1)
        print('Font Awesome subset up to date (%d icons)' % len(names))
        return
    build(css, known, names)


if __name__ == '__main__':
    main()
